#!/bin/bash



current_db="$2"
if [[ $current_db == '' ]]; then
	echo -e "\033[30;41mError: Database is not selected, Sir!\033[0m"
	exit
fi



get_column_datatype() {
    local metadataFile="$1"
    local target="$2"
    local index

    index=$(get_column_index "$metadataFile" "$target") || exit 1

    IFS=':' read -ra types < <(sed -n '2p' "./$current_db/$metadataFile")

    echo "${types[$index]}"
}


get_column_index() {
    local metadataFile="$1"
    local target="$2"
    target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

    IFS=':' read -ra cols < <(sed -n '1p' "./$current_db/$metadataFile")

    for i in "${!cols[@]}"; do
        col="${cols[$i]}"
        col=$(echo "$col" | tr '[:upper:]' '[:lower:]')

        if [[ "$col" == "$target" ]]; then
            echo "$i"
            return 0
        fi
    done

    echo -e "\033[30;41mError: Column ($target) not found, Sir!\033[0m" >&2
    exit 1
}


is_valid_datatype() {
	    local dtype="$1"
	    dtype="${dtype,,}"
	    if [[ ! ("$dtype" == "int" || "$dtype" == "varchar") ]]; then
		    echo -e "\033[30;41mInvalid Datatype ($dtype), Sir!\033[0m"
		    exit
	    fi
		}

column_exists() {
	local -n arr="$1"
	local target="$2"
	local not_found=1


	target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

	for col in "${arr[@]}"; do
		col=$(echo "$col" | tr '[:upper:]' '[:lower:]')
		if [[ "$col" == "$target" ]]; then
			not_found=0
			break
		fi
	
	done
	if [[ $not_found == 1 ]]; then
		echo -e "\033[30;41mError: Column ($target) is not found, Sir!\033[0m"
		exit
	fi
}


table_exists() {
	local arr=( $(find ./$current_db -maxdepth 1 -type f -printf "%f\n") )
	local target="$1"
	not_found=1

	target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

	for tbl in "${arr[@]}"; do
		tbl=$(echo "$tbl" | tr '[:upper:]' '[:lower:]')
		if [[ "$tbl" == "$target" ]]; then
			not_found=0
			break
		fi
	done

	if [[ $not_found == 1 ]]; then
		echo -e "\033[30;41mError: Table ($target) is not found, Sir!\033[0m"
		exit
	fi
}

delete_record_query="$1"
delete_record_lower=$(echo $delete_record_query | tr '[:upper:]' '[:lower:]')

table_name=$(echo $delete_record_query | awk '{print $3}')
metadataFile=".$table_name"
where=$(echo $delete_record_lower | awk '{print $4}')

if [[ $delete_record_lower == "delete from "* && $where == "where" ]]; then
	table_exists $table_name
        IFS=':' read -ra meta_column_names < <(sed -n '1p' "./$current_db/$metadataFile")
	IFS=':' read -ra meta_datatypes < <(sed -n '2p' "./$current_db/$metadataFile")

	column_name=$(echo $delete_record_query | awk '{print $5}')
	column_exists meta_column_names $column_name

	idx=$(get_column_index $metadataFile $column_name)

	datatype=$(get_column_datatype $metadataFile $column_name)

	operator=$(echo $delete_record_query | awk '{print $6}')

	value=$(echo $delete_record_query | awk '{print $7}')


	case "$operator" in
    	"=")
        	awk_cond='$col == value'
        	;;
    	"!=")
        	awk_cond='$col != value'
        	;;
    	">")
        	awk_cond='$col > value'
        	;;
    	"<")
        	awk_cond='$col < value'
        	;;
    	">=")
        	awk_cond='$col >= value'
        	;;
    	"<=")
        	awk_cond='$col <= value'
        	;;
	*)
		echo -e "\033[30;41mError: Invalid Operator ($operator), Sir!\033[0m"
		exit
		;;
	esac


	awk_col=$((idx + 1))

elif [[ $delete_record_lower == "delete from "* && $where == "" ]]; then
	table_exists $table_name
	IFS=':' read -ra meta_column_names < <(sed -n '1p' "./$current_db/$metadataFile")
	IFS=':' read -ra meta_datatypes < <(sed -n '2p' "./$current_db/$metadataFile")
	awk_cond='1 == 1'
else
	echo -e "\033[30;41mError: Check your Syntax, Sir!\033[0m"	
	exit
fi

touch 123

awk -F: -v col="$awk_col" -v value="$value" '
'"$awk_cond"' { next }
{ print }
' "./$current_db/$table_name" > 123

cat 123 > "./$current_db/$table_name"
rm 123


echo -e "\033[30;42mRecords deleted successfully, sir!\033[0m"
	
: <<'END_COMMENT'

END_COMMENT





