#!/bin/bash



is_invalid_name() {
	    local str="$*"
	    if [[ $str =~ ^[0-9] || $str =~ [[:space:]] || $str =~ [^a-zA-Z0-9_] ]]; then
		    echo "Error: Invalid Naming"
		    exit
	    fi
    }

is_valid_datatype() {
	    local dtype="$1"
	    dtype="${dtype,,}"
	    if [[ ! ("$dtype" == "int" || "$dtype" == "varchar") ]]; then
		    echo "Invalid Datatype: $dtype"
		    exit
	    fi
		}



column_exists() {
	local -n arr="$1"
	local target="$2"

	target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

	for col in "${arr[@]}"; do
		col=$(echo "$col" | tr '[:upper:]' '[:lower:]')
		if [[ "$col" == "$target" ]]; then
			echo "Error: Repeated Column Name"
			exit
		fi
	done
}


table_exists() {
	local arr=($(ls))
	local target="$1"

	target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

	for col in "${arr[@]}"; do
		col=$(echo "$col" | tr '[:upper:]' '[:lower:]')
		if [[ "$col" == "$target" ]]; then
			echo "Error: Table already exists"
			exit
		fi
	done
}

create_table_query="$*"
create_table_lower=$(echo $create_table_query | tr '[:upper:]' '[:lower:]')

if [[ $create_table_lower == "create table "* ]]; then

	table_name=$(echo $create_table_query | awk '{print $3}')
	is_invalid_name $table_name
	table_exists $table_name

	columns=$(echo "$create_table_query" | awk '{ $1=""; $2=""; $3=""; sub(/^ +/, ""); print }')

	if [[ ! $columns =~ ^\(.*\)$ ]]; then
		echo "Syntax Error"
		exit
	fi

	clean=${columns#(}
	clean=${clean%)}


	col_names=()
	col_types=()
	constraints=()

	IFS=',' read -ra cols <<< "$clean"

	pk=-1
	for line in "${cols[@]}"; do
		name=$(echo "$line" | awk '{print $1}')
		type=$(echo "$line" | awk '{print $2}')
		constraint=$(echo "$line" | awk '{ $1=""; $2=""; sub(/^ +/, ""); print }')
		constraint_lower=$(echo "$constraint" | tr '[:upper:]' '[:lower:]')

		if [[ ! ("$constraint_lower" == "primary key" || -z $constraint) ]]; then
			echo "Invalid Constraint"
			exit
		elif [[ "$constraint_lower" == "primary key" ]]; then
			pk=$((pk+1))
		fi

		if [[ pk > 0 ]]; then
			echo "Error: No more than one primary key"
			exit
		fi

		is_invalid_name $name
		column_exists col_names $name
		is_valid_datatype $type

		col_names+=("$name")
		col_types+=("$type")
		constraints+=("$constraint")
	done

	touch "$table_name" ".$table_name"

	(IFS=":"; echo "${col_names[*]}") > ".$table_name"
	(IFS=":"; echo "${col_types[*]}") >> ".$table_name"
	(IFS=":"; echo "${constraints[*]}") >> ".$table_name"


fi

