#!/bin/bash

check_prim(){
	local tableName="$1"
	local pkCol="$2"
	local value="$3"

	local metaFile=".${tableName}"
	local dataFile="$tableName"

	if [[ ! -f "$metaFile" ]]
	then
		echo "The metadata file of table '$tableName' not found."
		return 1
	fi

	if [[ ! -f "$dataFile" ]]
	then
		return 0
	fi

	IFS=':' read -ra columns < <(sed -n '1p' "$metaFile")

	local index=-1
	for i in "${!columns[@]}"
	do
		if [[ "${columns[$i]}" == "${pkCol,,}" ]]
		then
			index=$i
			break
		fi
	done

	if [[ index -eq -1 ]]
	then
		echo "Column '$pkCol' doesn't exist in table '$tableName'."
		return 1
	fi

	while IFS=':' read -ra row
	do
		if [[ "${row[$index]}" == "$value" ]]
		then
			return 1
		fi
	done < "$dataFile"

	return 0

}

if check_prim "test" "id" "1"
then
	echo "okay"
else
	echo "exist"
fi
