#!/bin/bash
echo -e "\033[94m"

cat << EOF | awk 'NR==11 {print "\033[33m" $0 "\033[0m"; next}1'


                     _____        _     _           _____  ____  
                    |  __ \      | |   | |         |  __ \|  _ \ 
                    | |  | | ___ | |__ | |__  _   _| |  | | |_) |
                    | |  | |/ _ \| '_ \| '_ \| | | | |  | |  _ < 
                    | |__| | (_) | |_) | |_) | |_| | |__| | |_) |
                    |_____/ \___/|_.__/|_.__/ \__, |_____/|____/ 
                                               __/ |             
                                              |___/             "Dobby has no master! Dobby is a free elf, and Dobby has come to save Harry Potter and his friends!" 
														      • By Salma Hamed Algayar & Farida Emad Alden •


EOF

sleep 0.5

IFS=""

while true; do
#	echo -e "\033[94m"
	echo ""
	buff=''
	IFS=""
	prompt="DobbyDB ♥ "
	while IFS= read -e -p $prompt -r line; do
		prompt="          "
		line=$(echo $line | sed 's/^[ \t]*//;s/[ \t]*$//')
		buff+="$line "
		[[ $line == "bye bye" ]] && exit;
		[[ $line == *";" ]] && break;
	done

#	echo -e "\033[46m"
	query=$(echo "${buff::-2}" | sed 's/^[ \t]*//;s/[ \t]*$//')
#	echo $query
	query=$(echo $query | sed "s/(/ (/g" | tr -s " " | sed "s/ ,/,/g" | sed "s/, /,/g" | sed "s/( /(/g" | sed "s/ )/)/g")
#	echo "neat query: $query"
	
	
	shopt -s nocasematch
	case "$query" in
		create\ database\ *)
			echo "Create database"
			./create_database $query
			;;
		drop\ database\ *)
			echo "Drop Database"
			;;
		show\ databases)
			echo "Show Databases"
			;;
		create\ table\ *)
			echo "Create Table"
			./create_table $query
			;;
		insert\ into\ *)
			echo "Insert Record"
			./insert_record $query
			;;
		delete\ from\ *)
			echo "Delete Record"
			./delete_records $query
			;;
		update\ *)
			echo "Update Record"
			./update_record $query
			;;
		select\ *)
			echo "Select Records"
			./select_record $query
			;;
		show\ tables)
			echo "Show Tables"
			;;
		drop\ table\ *)
			echo "Drop Table"
			./drop_list_tables $query
			;;
		*)
			echo -e "\033[31mInvalid Query, Sir!\033[0m"
	esac
done
: END COMMENT '
'
END COMMENT

#./create_table "$query_"
#./insert_record "$query_"


