#!/bin/bash

fullQuery=$1

read -ra words <<< "$fullQuery"
wordCount=${#words[@]}

database=0
if [[ ${words[0],,} == "create" ]]
then
	if [[  ${words[1],,} == "database"  && $wordCount -eq 3 ]]
	then
		exist=0
		dirs=( $(basename -a ~/DBMS/DobbyDb3/*/))
		for dir in ${dirs[@]}
		do
			echo 
			if [[ "${words[2],,}" = "${dir,,}" ]]
			then
				exist=1
				break
			fi
		done
		if [ $exist -eq 0 ]
		then
			if [[  ${words[2],,} =~ ^[0-9] ||  ${words[2],,} =~ [[:space:]] ||  ${words[2],,} =~ [^a-zA-Z0-9_] ]]
			then
				echo "Invalid name for Database"
				exit
			fi
			mkdir "${words[2],,}"
			echo "Database Created"
		else
			echo "Database Already Exist"
		fi
	else
		echo "Invalid Syntax"
	fi
elif [[ ${words[0],,} == "use" &&  $wordCount -eq 2 ]]
then
	exist=0
	dirs=( $(basename -a ~/DBMS/DobbyDb3/*/))
	for dir in ${dirs[@]}
	do
		if [[ "${words[1],,}" == "${dir,,}" ]]
		then
			exist=1
			break
		fi
	done
	if [ $exist -eq 1 ]
	then
		database=${words[1],,}
		echo $database
	else
		echo "Database Doesn't Exist"
	fi
elif [[ ${words[0],,} == "drop" ]]
then
	if [[ ${words[1],,} == "database" &&  $wordCount -eq 3 ]]
	then
		exist=0
		dirs=( $(basename -a ~/DBMS/DobbyDb3/*/))
		for dir in ${dirs[@]}
		do
			if [[ "${words[2],,}" = "${dir,,}" ]]
			then
				exist=1
				break
			fi
		done
		if [ $exist -eq 1 ]
		then
			rm -r "${words[2],,}"
			echo "Database Deleted"
		else
			echo "Database Doesn't Exist"
		fi
	else
		echo "Invalid Syntax"
	fi
elif [[ ${words[0],,} == "show" ]]
then
	if [[ ${words[1],,} == "databases" &&  $wordCount -eq 2 ]]
	then
		exist=0
		dirs=( $(basename -a ~/DBMS/DobbyDb3/*/))
		for dir in ${dirs[@]}
		do
			echo $dir
		done
	fi
else
	echo "Invalid Syntax"
fi
