#!/bin/bash

validate_value_datatype() {
    local datatype="$1"
    local value="$2"

    case "$datatype" in
        int)
            # must be a valid integer (no quotes allowed)
            if [[ "$value" =~ ^-?[0-9]+$ ]]; then
                    echo "GOOD $datatype"
                return 0
            else
                echo "Error: Value '$value' is not a valid INT"
                exit 1
            fi
            ;;

        varchar)
            # varchar values must be quoted: 'text' or "text"
            if [[ "$value" =~ ^\".*\"$ || "$value" =~ ^\'.*\'$ ]]; then
                    echo "GOOD $datatype"
                return 0
            else
                echo "Error: Value '$value' must be quoted for VARCHAR"
                exit 1
            fi
            ;;

        *)
            echo "Error: Unknown datatype '$datatype'"
            exit 1
            ;;
    esac
}

get_column_index() {
    local metadataFile="$1"
    local target="$2"
    target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

    # Read first line (column names)
    IFS=':' read -ra cols < <(sed -n '1p' "$metadataFile")

    for i in "${!cols[@]}"; do
        col="${cols[$i]}"
        col=$(echo "$col" | tr '[:upper:]' '[:lower:]')

        if [[ "$col" == "$target" ]]; then
                echo "$((i+1))"
            return 0
        fi
    done

    echo "Error: Column '$target' not found" >&2
    exit 1
}

pk_violation() {
        local table_name="$1"
        IFS=':' read -ra cols < <(sed -n '1p' ".$table_name")

        for col in "${cols[@]}"; do
                col=$(echo "$col" | tr '[:upper:]' '[:lower:]')
                if ./is_primary_key "$col" "$table_name"; then
                        pk_idx=$(get_column_index ".$table_name" $col)
                        count_all=$(cat 123 | awk -F":" ' BEGIN {count=0} {count++} END {print count}')
			count_distinct=$(awk -F":" -v pk_idx="$pk_idx" '
    			{ seen[$pk_idx]++ }
    			END { print length(seen) }
			' "123")

                        if [[ $count_all != $count_distinct ]]; then
                                echo "Error: Primary Key Uniqueness Violation"
				rm 123
                                exit
                        fi
                        break
                fi

        done
}

is_valid_datatype() {
	    local dtype="$1"
	    dtype="${dtype,,}"
	    if [[ ! ("$dtype" == "int" || "$dtype" == "varchar") ]]; then
		    echo "Invalid Datatype: $dtype"
		    exit
	    fi
		}

column_exists() {
	local -n arr="$1"
	local target="$2"

	target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

	for col in "${arr[@]}"; do
		col=$(echo "$col" | tr '[:upper:]' '[:lower:]')
		if [[ "$col" == "$target" ]]; then
			break
		fi
	
	done
}


table_exists() {
	local arr=($(ls))
	local target="$1"
	not_found=1

	target=$(echo "$target" | tr '[:upper:]' '[:lower:]')

	for tbl in "${arr[@]}"; do
		tbl=$(echo "$tbl" | tr '[:upper:]' '[:lower:]')
		if [[ "$tbl" == "$target" ]]; then
			not_found=0
			break
		fi
	done

	if [[ $not_found == 1 ]]; then
		echo "Error: Table not found"
		exit
	fi
}

insert_record_query="$*"
#insert_record_query="INSERT INTO test (id,name,age) VALUES (15,'Saleym',19)"
insert_record_lower=$(echo $insert_record_query | tr '[:upper:]' '[:lower:]')

echo $insert_record_lower

val=$(echo $insert_record_lower | awk '{print $5}')
echo $val

if [[ $insert_record_lower == "insert into "* && $val == "values" ]]; then
	table_name=$(echo $insert_record_query | awk '{print $3}')
	table_exists $table_name

	metadataFile=".$table_name"

	IFS=':' read -ra meta_column_names < <(sed -n '1p' "$metadataFile")
	IFS=':' read -ra meta_datatypes < <(sed -n '2p' "$metadataFile")
	IFS=':' read -ra meta_constraints < <(sed -n '3p' "$metadataFile")

	echo "${meta_column_names[@]}"
	echo "${meta_datatypes[@]}"
	echo "${meta_constraints[@]}"

	columns=$(echo "$insert_record_query" | awk '{ print $4 }')
	
	if [[ ! $columns =~ ^\(.*\)$ ]]; then
		echo "Syntax Error"
		exit
	fi

	clean=${columns#(}
	clean=${clean%)}

	IFS=',' read -ra user_column_names <<< "$clean"

	values=$(echo "$insert_record_query" | awk '{ print $6 }')

	if [[ ! $values =~ ^\(.*\)$ ]]; then
		echo "Syntax Error"
		exit
	fi

	clean=${values#(}
	clean=${clean%)}

	IFS=',' read -ra user_values <<< "$clean"

	echo "${user_column_names[@]}"
	echo "${user_values[@]}"

	sorted_metadata_column_names=$(printf "%s\n" "${meta_column_names[@]}" | sort | tr '\n' ' ')
	sorted_user_column_names=$(printf "%s\n" "${user_column_names[@]}" | sort | tr '\n' ' ')

	if [[ "$sorted_metadata_column_names" != "$sorted_user_column_names" ]]; then
		    echo "Error: Column mismatch, Supply all columns"
		        exit
	fi





	declare -A map

	for i in "${!user_column_names[@]}"; do
		key="${user_column_names[$i]}"
		map["$key"]="${user_values[$i]}"

		echo $i
		echo $key
		echo ${map[$key]}
      	done
	

	ordered_values=()
	for col in "${meta_column_names[@]}"; do
		echo "-----------"
		echo $col
		ordered_values+=("${map[$col]}")
		echo ${ordered_values[@]}
	done

	echo "Ordered_values: ${ordered_values[@]}"
	echo ${ordered_values[@]}

	for i in "${!meta_datatypes[@]}"; do
		echo $i
		dt="${meta_datatypes[$i]}"
		echo "DataType :)) $dt"
		val="${ordered_values[$i]}"
		echo $val
#		clean_val=$(echo "$val" | sed 's/^"//;s/"$//')
#		echo $clean_val
		validate_value_datatype $dt $val

		val_clean="${val%\"}"; val_clean="${val_clean#\"}"
		val_clean="${val_clean%\'}"; val_clean="${val_clean#\'}"

		ordered_values[$i]=$val_clean
	done




	touch 123
	cat $table_name > 123

	record=$(IFS=':'; echo "${ordered_values[*]}")
	echo "$record" >> 123
	
	pk_violation $table_name

	cat 123 > $table_name
        rm 123


: <<'END_COMMENT'

END_COMMENT
fi


